name: Trigger auto deployment for mycontainerapp17022025

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mycontainerapp17022025-AutoDeployTrigger-ea166229-e4d8-4f35-8dd7-e51d4004d68c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYCONTAINERAPP17022025_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYCONTAINERAPP17022025_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYCONTAINERAPP17022025_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.MYCONTAINERAPP17022025_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYCONTAINERAPP17022025_REGISTRY_PASSWORD }}
          containerAppName: mycontainerapp17022025
          resourceGroup: anandatheerthan
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


